### PR TITLE
Set scripts as executable, output commands run in deploy script

### PR DESCRIPTION
**Pull request by justinharringa**
@dilipdevaraj-sfdc This will give us some more information (and bring in my previous PR). The execution permissions may also fix the issue. I've directed this to `develop` so that it gets there. Then you can merge it to `master`.

### CODE REVIEW

**Comment by dilipdevaraj-sfdc** [comment]
@justinharringa 
I merged the last PR from you to master.
The build ran and it shows as success https://travis-ci.org/salesforce/Argus/builds/394376492
But I don't see the artifact publishing in log , nor can I see it in maven
https://mvnrepository.com/artifact/com.salesforce.argus/argus

Do you know what may be going on from logs?

**Comment by justinharringa** [comment]
😢 - looks like Coverity blocked it now...
```
$ pip install --user codecov
Coverity Scan analysis selected for branch master.
Coverity Scan analysis NOT authorized until Wed, 20 Jun 2018 20:54:38 +0000 UTC.
```

**Comment by dilipdevaraj-sfdc** [comment]
@justinharringa 
It is failing to deploy with message "/home/travis/build/salesforce/Argus/.travis.deploy.sh: source: not found"
See https://api.travis-ci.org/v3/job/394376493/log.txt

**Comment by justinharringa** [comment]
@dilipdevaraj-sfdc yeah, I saw that. :( I'm going to put together a test project to get this all straightened out and see if I can't get you a new PR. May not be today though.

**Comment by justinharringa** [comment]
@dilipdevaraj-sfdc I think I've got this fixed up in  https://github.com/salesforce/Argus/pull/768

**Pull request merged**
