### PR TITLE
Call .travis.deploy.sh w/bash and use curly braces

### PR DESCRIPTION
**Pull request by justinharringa**
`sh` in Travis seems to work a little differently than on CentOS and switching to `bash` seems to bring consistency and more support back (as evidenced by experimentation done in [a simple travis-source project I put together to test this](https://travis-ci.org/justinharringa/travis-source))

### CODE REVIEW

**Comment by justinharringa** [comment]
@dilipdevaraj-sfdc are you still looking to get this merged into master?

**Comment by dilipdevaraj-sfdc** [comment]
The process followed is - will be merged to master after the most up to date release deployment is qualified.

**Comment by justinharringa** [comment]
I see so I guess this won't make your 2.15 release or you're pushing that
release back?

**Comment by dilipdevaraj-sfdc** [comment]
If code is already part of 2.15 branch it will be deployed to production. Once this build is qualified the branch will be merged to master at the last stage (this is so that master is always a working branch of latest branch)
cc @sundeepsf

**Comment by sundeepsf** [comment]
yes, this will go into production next week

**Comment by justinharringa** [comment]
Cool. Thanks for the background 😄

**Pull request merged**
