### PR TITLE
updates for chart options

### PR DESCRIPTION
**Pull request by cnardi-dev**
Chart updates upon selection inside modal and includes functionality for:

- Date formats
- Y-axis tick format and # (X axis options have been removed)
- Truncation options for metric name displayed in Legend.  Tooltip still needs setup
- Downsampling options
- Brushing & Zooming options
- Tooltip sorting
- Display raw data for datapoint value (tooltip)
- Custom format for datapoint value (tooltip)

Still outstanding:

- Color palette options
- Move Synchronize options to modal
- Apply settings to all graphs
- Reset to default settings

### CODE REVIEW

**Comment by prestonfff** [comment]
The Zooming and brushing toggle seems not stored after page refresh. I'm taking a look at it.

**Comment by cnardi-dev** [comment]
color scheme settings are not complete yet.

**Comment by xizi-xu** [comment]
The close window icon on the modal does not work for me. Anyone else has this issue?

**Comment by cnardi-dev** [comment]
bug related to tooltip does not hide when mouse out.

**Pull request merged**
