### PR TITLE
Bloom Filter changes to support caching of metric schema before writing to ES

### PR DESCRIPTION
**Pull request by dilipdevaraj-sfdc**

### CODE REVIEW

**Comment by nkunal** [comment]
hi

**Comment by nkunal** [comment]
hi

**Comment by dilipdevaraj-sfdc** [comment]
@kgowdru 
PR has been approved by nkunal. But he does not have write access. Can you add nkunal as member.
 If PR looks good to you can you approve it so I can merge it.

**Comment by rajsarkapally** [comment]
@dilip-devaraj  approved

**Pull request merged**
