### PR TITLE
Improving Discovery schema service performance

### PR DESCRIPTION
**Pull request by rajsarkapally-sfdc**

### CODE REVIEW

**Comment by bsura** [comment]
@rajsarkapally-sfdc There is a compilation error. Did you forget to check-in a file or something?

**Comment by rajsarkapally-sfdc** [comment]
@bsura Missed some files and checked in just now. Now build passed.

**Comment by rajsarkapally-sfdc** [comment]
@dilipdevaraj-sfdc @bsura Can you please review this?

**Comment by bsura** [comment]
Yes. I am. I have a few questions. Let's discuss them offline.

**Pull request merged**
