### PR TITLE
Finding shared alerts, dashboards with filtering by owner

### PR DESCRIPTION
**Pull request by dilipdevaraj-sfdc**

### CODE REVIEW

**Comment by dilipdevaraj-sfdc** [comment]
@bsura @rajsarkapally 
Can you please review part 1 of finding shared dashboards alerts.

**Comment by bsura** [comment]
I thought we were implementing a new version of the API. Is that going to come out separately?

**Comment by dilipdevaraj-sfdc** [comment]
@bsura 
Yes that will be a separate commit.
I wanted to send a PR on work done as long as it is complete functional, in spirit of committing small changes and frequently. So we don't have  to do a merge while waiting for completed story.

This is for just
Gets all shared alert/dashboard owned by anyone in Argus system 
/alert/shared 
/alert/shared/meta 
/dashboard/shared 
/dashboard/shared/meta 

Will add other endpoints as discussed once I am done with federation story. 
-----------------
Gets only users alerts/dashboards that can then be filtered by alert/dashboard name and shared status using query params 
v2/alert 
v2/alert/meta 
v2/dashboard 
v2/dashboard/meta 
----------------
Makes sense ?

**Comment by dilipdevaraj-sfdc** [comment]
Sure will do.

**Comment by dilipdevaraj-sfdc** [comment]
@bsura As discussed, this PR is a non breaking change since only new endpoints are added, so it should be good for further code review.

**Comment by bsura** [comment]
Ok I'll take a look.

**Pull request merged**
