### PR TITLE
Creating RPM files

### PR DESCRIPTION
**Pull request by rajsarkapally-sfdc**

### CODE REVIEW

**Comment by saaja-sfdc** [comment]
Yes

**Comment by saaja-sfdc** [comment]
Although we use BSD 3 clause,  not gpl

**Comment by dilipdevaraj-sfdc** [comment]
@rajsarkapally-sfdc @saaja-sfdc 
I am not able to merge this specific pull request alone. It says "Required statuses must pass before merging", but there is no code coverage change since these are SPEC build changes.

Can one of you take a look.

**Comment by rajsarkapally-sfdc** [comment]
@saaja-sfdc  Merge pull request button is also disabled for me.

**Pull request merged**
