### PR TITLE
Add new ag-table 

### PR DESCRIPTION
**Pull request by prestonfff**
- Pagination with truncation
- Search feature
- Sort across row
- Scrollable table area
- Fixed header for top row and left column
- Support ag-option title.text
- No need to have itemsPerpage in ag-option because user can interactively set that 
- Option storage for the table

### CODE REVIEW

**Comment by cnardi-dev** [comment]
Note: build failed due to same Docker file issue with command for bower.  I can update the 3-1 branch with develop branch and get the build fixed.

**Comment by xizi-xu** [comment]
@saaja-sfdc do you mind to re run the test?

**Comment by cnardi-dev** [comment]
not sure how we can re-run the tests other than pushing another commit to this PR.

**Comment by bsura** [comment]
I restarted the build.

**Comment by cnardi-dev** [comment]
How did you restart the build?  So we can do this next time?

**Comment by bsura** [comment]
There's a Restart Build button on the top right corner. I think only few of us have access. @saaja-sfdc can enable it for you I guess.

**Pull request merged**
